# Generated by Django 5.2.12 on 2026-03-28 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0002_presence_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userpresence',
            new_name='presence_us_is_onli_81bb35_idx',
            old_name='presence_online_idx',
        ),
    ]
