# Generated by Django 5.2.12 on 2026-03-28 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(blank=True, max_length=20, unique=True)),
                ('title', models.CharField(max_length=180)),
                ('body_markdown', models.TextField()),
                ('released_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-released_at'],
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
                ('url', models.URLField()),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('terms', 'Terms of Service'), ('privacy', 'Privacy Policy'), ('cookies', 'Cookie Policy')], max_length=20, unique=True)),
                ('version', models.CharField(default='v1', max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('body_markdown', models.TextField()),
                ('published_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['doc_type'],
            },
        ),
        migrations.CreateModel(
            name='SiteBranding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='dChat', max_length=120)),
                ('theme_preset', models.CharField(choices=[('default', 'Default'), ('dekcx', 'dekcx')], default='default', max_length=32)),
                ('logo_url', models.URLField(blank=True)),
                ('accent_hex', models.CharField(default='#f39c12', max_length=7)),
                ('bg_hex', models.CharField(default='#0f1217', max_length=7)),
                ('surface_hex', models.CharField(default='#1a1f29', max_length=7)),
                ('text_hex', models.CharField(default='#e5e7eb', max_length=7)),
                ('muted_text_hex', models.CharField(default='#9ca3af', max_length=7)),
                ('link_hex', models.CharField(default='#7cc4ff', max_length=7)),
                ('border_radius_px', models.PositiveSmallIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SetupState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserLegalConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_version', models.CharField(blank=True, max_length=20)),
                ('privacy_version', models.CharField(blank=True, max_length=20)),
                ('cookies_version', models.CharField(blank=True, max_length=20)),
                ('accepted_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'terms_version', 'privacy_version', 'cookies_version')},
            },
        ),
    ]
