# Generated by Django 5.2.12 on 2026-03-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitebranding',
            name='klipy_app_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sitebranding',
            name='klipy_content_filter',
            field=models.CharField(default='medium', max_length=16),
        ),
    ]
