# Generated by Django 5.2.12 on 2026-03-28 03:53

import apps.core.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dm', '0004_directmessageattachment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='directconversation',
            new_name='dm_directco_updated_0a9381_idx',
            old_name='dm_convo_updated_idx',
        ),
        migrations.RenameIndex(
            model_name='directmessage',
            new_name='dm_directme_convers_dc3837_idx',
            old_name='dm_message_convo_idx',
        ),
        migrations.RenameIndex(
            model_name='directmessage',
            new_name='dm_directme_recipie_955bac_idx',
            old_name='dm_message_recipient_idx',
        ),
        migrations.AlterField(
            model_name='directmessageattachment',
            name='file',
            field=models.FileField(upload_to=apps.core.uploads.SanitizedUploadPath('dm-attachments')),
        ),
    ]
